pipeline {
    agent any

    stages {
        stage ('Plan') {
            steps {
                teeraform -version
                // terraform init
                // terraform plan
            }
        }

        stage ('Apply') {
            steps {
                input ('Approve?')
                terraform -version
                // terraform init
                // terraform apply -auto-approve
            }
        }
    }
}

