pipeline {
    agent any

    stages {
        stage ('Plan') {
            steps {
                bat '''
                    terraform init
                    terraform plan
                '''
            }
        }

        stage ('Apply') {
            steps {
                input ('Approve?')
                bat '''
                    terraform init
                    terraform apply -auto-approve
                '''
            }
        }
    }
}

